### ISSUE TITLE
Error about invalid argument "-component.UseLocalHostAsDefaultHost"

### ISSUE THREAD

**Issue by SoerenHenning** [Dynatrace/dynatrace-otel-collector#311]
**Describe the bug**

With the latest release (v0.15.0), I get the following error in all OTel collector pods when deploying with the OpenTelemetry Operator:

```
$ kubectl logs dynatrace-otel-collector-...
Error: invalid argument "-component.UseLocalHostAsDefaultHost" for "--feature-gates" flag: feature gate "component.UseLocalHostAsDefaultHost" is stable, can not be disabled
2024/09/27 12:32:55 collector server run finished with error: invalid argument "-component.UseLocalHostAsDefaultHost" for "--feature-gates" flag: feature gate "component.UseLocalHostAsDefaultHost" is stable, can not be disabled
```
My deployment is mostly aligned with the [Dynatrace OTel collector deployment docs](https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/collector/deployment), with the main difference that I use `mode: "daemonset"` (see below). With v0.14.0 everything works fine.

I assume this is related to https://github.com/open-telemetry/opentelemetry-operator/issues/3306.

**To Reproduce**

I deploy the Dynatrace OTel Collector with the OpenTelemetry Operator according to the steps described in [Dynatrace OTel collector deployment docs](https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/collector/deployment) with _Deploy as an agent (DaemonSet)_. My `OpenTelemetryCollector` manifest looks like this:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dynatrace-otel
spec:
  envFrom:
  - secretRef:
      name: dynatrace-otelcol-dt-api-credentials
  env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  mode: "daemonset"
  image: "ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest"
  #...
```

**Expected behavior**
I expected that on each Kubernetes node a pod `dynatrace-otel-collector-...` is successfully started.

**Additional context**
I am using Kubernetes version 1.29 in AWS EKS.
